# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
parchment_mappings=1.21.1:2024.11.17
loader_version=0.16.14

# Mod Properties
mod_version=1.8.2
maven_group = de.dafuqs
archives_base_name = SpectralDecorations

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.116.4+1.21.1
spectrum_version=1.10.2

cloth_config_version=15.0.140
modmenu_version=11.0.3
rei_version=16.0.799
emi_version=1.1.22+1.21.1
architectury_version=13.0.8
modonomicon_version=1.117.2
trinkets_version=3.10.0
cca_version=6.1.2
additional_entity_attributes_version=2.0.0+1.21.1
revelationary_version=1.3.9+1.21.1
fractal_version=1.3.0+1.21.1
arrowhead_version=1.4.4+1.21.1
dimensional_reverb_version=1.1.0+1.21.1
colorful_hearts_version=10.3.8
sodium_version=mc1.21.1-0.6.13-fabric
cpa_version=1.0.0
ears_version=1.4.7
idwtialsimmoedm_version=0.3.2+1.21
travelers_backpack_version=Mse7s79Y
botania_version=1.20.1-448-fabric
auth_me_version=D0QqKqZn
create_version=0.5.1-j-build.1631+mc1.20.1
neepmeat_version=0.13.0-beta+1.20.1
malum_version=1.20.1-1.6.3.0b-fabric
lodestone_version=1.20.1-1.6.2.3f
port_lib_version=2.3.8+1.20.1
port_lib_modules=lazy_registration
exclusionslib_version=R2vQMUlU
vanityslots_version=9oyPiBlw
starry_skies_version=3.2.0+1.21.1

# What recipe viewer to use ('emi', 'rei', or 'disabled')
recipe_viewer=emi