# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.debug=false
org.gradle.parallel=true
org.gradle.caching=true

## Environment Properties
minecraft_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neoforge_version=21.1.248
neoforge_version_range=[21.1.186,)

# Mod Properties
mod_id=spectral_decorations
mod_version=1.10.0-1.21.1-neo
maven_group=de.dafuqs
archives_base_name=SpectralDecorations

# Dependencies
spectrum_version=1.12.5-1.21.1-neo
spectrum_version_range=[1.12.5-1.21.1-neo,)
# https://maven.is-immensely.gay/#/releases/de/dafuqs/revelationary/revelationary
revelationary_version=1.5.0+1.21.1
revelationary_version_range=[1.5.0+1.21.1,)
# https://maven.is-immensely.gay/#/releases/de/dafuqs/fractal
fractal_version=1.8.2+1.21.1-neoforge
rei_version=16.0.799
emi_version=1.1.24+1.21.1

# What recipe viewer to use ('emi', 'rei', or 'disabled')
recipe_viewer=emi